#베이스 이미지를 명시해준다. 
#FROM baseImage

#추가적으로 필요한 파일들을 다운로드 받는다.
#RUN command

#컨테이너 시작시 실행 될 명령어를 명시해준다. 
#CMD ["executable"]

FROM alpine
CMD [ "echo" , "hello" ]

#도커 파일에 입력된 것들이 도커 클라이언트에 전달 되어서 도커 서버가 인식하게 하여야 한다. 
#-- docker build ./ or docker build .

#build 시키면 숫자로 imageID가 나옴 -- 이름을 줄 수 있게 설정가능 
#docker build -t tnswh2023/hello:latest
#-t dockerid/저장소or 프로젝트 이름 : version 
